"""Ajout des likes et commentaires

Revision ID: 901746c9d41a
Revises: 74bf8f29f358
Create Date: 2025-05-05 21:56:32.265196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901746c9d41a'
down_revision = '74bf8f29f358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
