"""Ajout des champs de profil

Revision ID: bcaf9ad31063
Revises: 
Create Date: 2025-05-05 16:32:00.736106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaf9ad31063'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nom', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pseudo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telephone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('telephone')
        batch_op.drop_column('photo')
        batch_op.drop_column('pseudo')
        batch_op.drop_column('nom')

    # ### end Alembic commands ###
